on: [push]

jobs:
  hello_world_job:
    runs-on: windows-2019
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: Arwinderorg2/Arwinderrepo3@v1
      with:
        who-to-greet: 'Arwinder Singh1'
